### PR TITLE
Update AI documentation

### PR DESCRIPTION
**Pull request by InAnYan**
I think the new documentation is not deployed right now?

I also found a `SUMMARY.md` file, where there was no AI. So I made a separate PR for this

### CODE REVIEW

**Comment by koppor** [comment]
This is a follow-up to https://github.com/JabRef/user-documentation/pull/491.

I do understand why here are so many changes. Need to look into it later.

**Comment by koppor** [comment]
I found the issue:

1. https://github.com/JabRef/user-documentation/pull/491 was squash-merged
2. This PR was based on the branch of https://github.com/JabRef/user-documentation/pull/491
3. A new commit [`ebcc0e1` (#497)](https://github.com/JabRef/user-documentation/pull/497/commits/ebcc0e1751fd2cbdc7b6efd22d072b86378b1b5c) was added

"Just" merging `main` fixes the issue of GitHub showing too much difference. - Always starting from `main` is also a workaround of the issue.

**Comment by koppor** [comment]
We do a bad job with our CONTRIBUTING guidelines.

Maybe you can help to move content from https://github.com/JabRef/user-documentation?tab=readme-ov-file#advanced-contribution-hints to https://github.com/JabRef/user-documentation/blob/main/en/contributing/how-to-improve-the-help-page.md. -- I think, it is "just" text moval?

**Comment by InAnYan** [comment]
Oliver, remember you told, that "Students don't think"

Student's (me) don't think :)

**Comment by InAnYan** [comment]
Ah, a squash-merge, I see. Sorry

**Pull request merged**
