### PR TITLE
Add snap/flatpak information

### PR DESCRIPTION
**Pull request by LyzardKing**
Add information related to the integration between jabref and external programs.
It might be a good idea to add a table with checks that can easily visualize the possible connections..

Something like this:
||Snap|Flatpak|deb/rpm|portable|
|Libreoffice|:x:|:x:|:heavy_check_mark:|:heavy_check_mark:|

Granted, it's not shown properly as markdown in the comment..but is it a good idea or is it just lost space on the page?

### CODE REVIEW

**Comment by Siedlerchr** [comment]
I like the idea! Btw, for tables I recommend something like this https://www.tablesgenerator.com/markdown_tables
or to generate the tables from 
https://jakebathman.github.io/Markdown-Table-Generator/

**Comment by LyzardKing** [comment]
I need to verify the integrations properly.
I'll comment here when the testing is done

**Comment by koppor** [comment]
@LyzardKing May I ask for an update? 😇

**Comment by LyzardKing** [comment]
Yes, sorry.. this slipped my mind.
It should be correct as it is, but give me tomorrow and I'll revisit it.

**Comment by LyzardKing** [comment]
ok @koppor 
At the moment this is the state of things, although a copy/paste always works.
In the future things might change, with the adoption of new integrations in the libreoffice packages, and the ability to call external programs from snaps/flatpaks.
For now this can be merged

**Comment by LyzardKing** [comment]
There seems to be some interesting discussion on a portal that can be used in flatpak to allow outside commands (like the tex editors) to be executed, but I need some time to check if it works or if there are issues.
For now this is the current status

**Pull request merged**
