### PR TITLE
Fix dead link

### PR DESCRIPTION
**Pull request by marcelm**
This hopefully makes CI green again.

### CODE REVIEW

**Comment by marcelm** [comment]
I tried ...

**Comment by tobiasdiez** [comment]
I think the whole paragraph about Library can be removed. It's not maintained for 4 years now, so it seems unlikely that it will come back and we probably shouldn't advertise it.

**Comment by marcelm** [comment]
Sure! I prefer that as well.

**Review by tobiasdiez — APPROVED** [review]
Thanks!

**Pull request merged**
