### PR TITLE
Add an help section for the management of keywords

### PR DESCRIPTION
**Pull request by mlep**
This is a first draft.
Please, correct/append/etc.

Note: screenshots and internal links will be added after merging (using gitbook).

### CODE REVIEW

**Comment by mlep** [comment]
Superseded by PR #312 
Closing.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
These changes are independent of #312?

**Comment by mlep** [comment]
Opps, I confused with other changes...
Reopening.

**Comment by tobiasdiez** [comment]
(you first need to restore the branch, before you can reopen the PR)

**Comment by koppor** [comment]
First text reads good. Screenshots can be added later.

**Pull request merged**
