### PR TITLE
Add new page for Custom Themes [advanced] for 5.2 (dev) #324

### PR DESCRIPTION
**Pull request by AtrusRiven**
Created pages for Custom Themes according to #324

### CODE REVIEW

**Review by koppor — COMMENTED** [review]
Short, but good enough. Could you fix the markdown lint issues?

```
 en/advanced/customthemes.md:1 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "# Custom Themes"]
en/advanced/customthemes.md:2 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## General"]
en/advanced/customthemes.md:9 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## Selection of Useful CSS selectors"]
en/advanced/customthemes.md:16 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "## Examples"]
```

(Reason for linting: I want to have all markdown files in this repository to look the same way. This IMHO enables better maintenance)

**Comment by AtrusRiven** [comment]
Done!

**Comment by Siedlerchr** [comment]
Do we still have those since version xxx headers or a way to mark the content for a specific version?

**Review by Siedlerchr — APPROVED** [review]
Thanks for describing the process!

**Comment by koppor** [comment]
Think, the version headers are gone with the migration to GitBook refs #178

**Pull request merged**
