### PR TITLE
Add documentation for regex escape

### PR DESCRIPTION
**Pull request by funnym0nk3y**
Added documentation according to [this issue](https://github.com/JabRef/jabref/issues/8371#issue-1090789648).

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]

**Comment by Siedlerchr** [comment]
thank you very much!

**Comment by ThiloteE** [comment]
Waaait xD I wanted to rephrase this. You don't have to enter a backslash for EVERY java regex command. Give me a little bit of time

**Comment by ThiloteE** [comment]
Also one day, i have to learn how to do a pull request, even if it is just for documentation...

**Comment by Siedlerchr** [comment]
@ThiloteE  Just go to the file you wan to modify and click edit. GitHub asks you then automatically.
Okay, if you want to rephrase it, I'll wait

**Comment by ThiloteE** [comment]
Proposal to change to:

```
Remember, Java treats `\` as an escape character, therefore if you want to include any backslash into your RegEx, you have to use `\\` instead of `\`. This includes expressions that include the backslah, e.g. `\p{Lu}`. The corresponding expression in Jabref therefore would be `\\p{Lu}`.
```

**Pull request merged**
