### PR TITLE
Overhaul Entry Editor Preview (#7093)

### PR DESCRIPTION
**Pull request by AtrusRiven**
Entry Editor Preview overhauled, added screenshots etc.

### CODE REVIEW

**Review by calixtus — APPROVED** [review]
LGTM, but we should keep in mind, that in the mid future we try to automate the process of taking screenshots with TestFX. @koppor knows more? But for now it's good.
Thanks.

**Comment by AtrusRiven** [comment]
Why LGTM?

**Comment by calixtus** [comment]
LGTM = "Looks good to me"

**Comment by AtrusRiven** [comment]
Interesting, knwon to me as "Literally Garbage To Me" ;-)

**Comment by koppor** [comment]
Automated screenshots: See https://github.com/JabRef/jabref/pull/6089 for code and discussions. Especially https://github.com/JabRef/jabref/pull/6089#issuecomment-603780005

**Pull request merged**
