### PR TITLE
Try to add github checker

### PR DESCRIPTION
**Pull request by Siedlerchr**

### CODE REVIEW

**Comment by koppor** [comment]
I think, the thing to try is the [GitHub super linter](https://github.com/github/super-linter). It also starts markdown-lint. The only drawback is that is does not call the link check. Note the difference at `t` and `k` at lint vs. link. linting vs. href-checking ^^.

**Comment by Siedlerchr** [comment]
The Super linter does not yet support the github checker interface

**Comment by koppor** [comment]
Could you provide me with more details on the "GitHub checker interface"?

With LaTeX the super linter the output looks as follows:

grafik

See https://github.com/texdoc/abschlussarbeit-mit-latex/pull/19

**Comment by koppor** [comment]
I think, it is https://developer.github.com/v3/checks/

**Comment by Siedlerchr** [comment]
Yep, that is the interface reviewdog for checkstyle uses as well. This has the advantage that it directly "comments" on the line where the issues are:
https://github.com/reviewdog/reviewdog
I could try maybe with this https://github.com/prologic/action-markdownlint

**Comment by koppor** [comment]
Alternatively, we could try to submit a PR to GitHub :p

**Pull request closed without merging**
