### PR TITLE
[WIP] Translation: Update

### PR DESCRIPTION
**Pull request by mlep**
More details for non-programmer users.
Technical info moved to the end.

### CODE REVIEW

**Review by Siedlerchr — APPROVED** [review]

**Comment by mlep** [comment]
I would like to add 2 screenshots to the directory 'user-documentation/tree/master/en/.gitbook/assets' using the github GUI.
After choosing the files, "Uploading 1 of 2 files " is displayed, but nothing else happen...
Any idea what is wrong?

**Comment by Siedlerchr** [comment]
Hmm. Gitbook is somehow weird maybe @tobiasdiez  has an idea

**Comment by mlep** [comment]
From https://github.com/JabRef/user-documentation/upload/master/en/.gitbook/assets
if I remove the dot in front of "gitbook" in the URL (https://github.com/JabRef/user-documentation/upload/master/en/gitbook/assets), the file upload works, but then I am afraid to commit (not knowing what I am doing).

**Comment by tobiasdiez** [comment]
@mlep I've send you a link to gitbook.

**Comment by mlep** [comment]
@tobiasdiez Thanks. 2 png files added to master branch through gitbook.
Not sure it is the proper way to do, but I guess the screenshots will be displayed after merging.

**Comment by tobiasdiez** [comment]
I'll merge now. Let's see if the picture appear or not. If not, then you can also add the pictures directly in the text in gitbook. That worked for me.

**Comment by mlep** [comment]
@tobiasdiez 
It worked when looking at github (https://github.com/JabRef/user-documentation/blob/master/en/faqcontributing/how-to-translate-the-ui.md)
But the webpage is not updated (https://docs.jabref.org/faqcontributing/how-to-translate-the-ui).
Any more action to take?

**Comment by tobiasdiez** [comment]
The pictures show up now for me. I think it needed a bit of time to sync.

Thanks @mlep !

**Comment by mlep** [comment]
Indeed, they do show up now!
OK,, now I know I simply need to wait for a few hours.

**Comment by koppor** [comment]
Tpyically, it should sync after 1 minute. Maybe, there were issues regaring the pictures. Who knows...

**Pull request merged**
